# Generated by Django 5.2.8 on 2025-12-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_created_at_cartitem_delete_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='menu_item',
        ),
    ]
