# Generated by Django 5.2.8 on 2025-12-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_created_at_cart_session_key_alter_cart_user'),
        ('menu', '0004_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.menuitem'),
        ),
    ]
